local M = {}

-- stylua: ignore
local Catppuccin = {
  yellow  = '#eed49f',
  red     = '#ed8796',
  magenta = '#f5bde6',
  blue    = '#8aadf4',
  cyan    = '#8bd5ca',
  green   = '#a6da95',
}

M.Colors = Catppuccin

-- stylua: ignore
M.Icons = {
  Action        = '',
  Array         = '',
  Boolean       = '◩',
  Bug           = '',
  Class         = '',
  CodeComment   = '',
  Codeium       = '',
  Color         = '',
  Comment       = '',
  Constant      = '󰏿',
  Constructor   = '',
  Enum          = '',
  EnumMember    = '',
  Error         = '',
  Event         = '',
  Field         = '',
  File          = '󰈙',
  Folder        = '',
  Function      = '󰊕',
  Hint          = '',
  Info          = '', -- 
  Interface     = '',
  Key           = '󰌋',
  Keyword       = '',
  Method        = '󰆧',
  Module        = '󰏖',
  Namespace     = '󰮴',
  Null          = '󰟢',
  Number        = '󰎠',
  Object        = '󰅩',
  Operator      = '',
  Other         = '',
  Package       = '󰏗',
  Property      = '',
  Reference     = '󰈇',
  Snippet       = '',
  String        = '',
  Struct        = '󰙅',
  Text          = '󰉿',
  TypeParameter = '',
  Unit          = '',
  Value         = '󰎠',
  Variable      = '',
  Warning       = '',
}

local macos = require('shirohana.config').USE_MACOS_OPT_KEYMAPS
M.Keys = {
  ['<M-,>'] = macos and '≤' or '<M-,>',
  ['<M-.>'] = macos and '≥' or '<M-.>',
  ['<M-1>'] = macos and '¡' or '<M-1>',
  ['<M-2>'] = macos and '™' or '<M-2>',
  ['<M-3>'] = macos and '£' or '<M-3>',
  ['<M-4>'] = macos and '¢' or '<M-4>',
  ['<M-5>'] = macos and '∞' or '<M-5>',
  ['<M-6>'] = macos and '§' or '<M-6>',
  ['<M-7>'] = macos and '¶' or '<M-7>',
  ['<M-8>'] = macos and '•' or '<M-8>',
  ['<M-9>'] = macos and 'ª' or '<M-9>',
  ['<M-:>'] = macos and 'Ú' or '<M-:>',
  ['<M-;>'] = macos and '…' or '<M-;>',
  ['<M-H>'] = macos and 'Ó' or '<M-H>',
  ['<M-J>'] = macos and 'Ô' or '<M-J>',
  ['<M-K>'] = macos and '' or '<M-K>',
  ['<M-L>'] = macos and 'Ò' or '<M-L>',
  ['<M-S>'] = macos and 'Í' or '<M-S>',
  ['<M-[>'] = macos and '“' or nil,
  ['<M-]>'] = macos and '‘' or nil,
  ['<M-b>'] = macos and '∫' or '<M-b>',
  ['<M-f>'] = macos and 'ƒ' or '<M-f>',
  ['<M-h>'] = macos and '˙' or '<M-h>',
  ['<M-j>'] = macos and '∆' or '<M-j>',
  ['<M-k>'] = macos and '˚' or '<M-k>',
  ['<M-l>'] = macos and '¬' or '<M-l>',
  ['<M-r>'] = macos and '®' or '<M-r>',
  ['<M-s>'] = macos and 'ß' or '<M-s>',
  ['<M-t>'] = macos and '†' or '<M-t>',
  ['<M-w>'] = macos and '∑' or '<M-w>',
}

return M
