tap "oven-sh/bun"

brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "neovim"
brew "powerlevel10k"
brew "ripgrep"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "alfred"
cask "polypane"

# Migrating...
#
# brew "ansible"
# brew "asimov"
# brew "bat"
# brew "btop"
# brew "bun"
# brew "cocoapods"
# brew "eza"
# brew "fnm"
# brew "fzf"
# brew "git-delta"
# brew "gitui"
# brew "gnu-sed"
# brew "gnupg"
# brew "google-cloud-sdk"
# brew "graphviz"
# brew "grep"
# brew "grip"
# brew "htop"
# brew "httpie"
# brew "jq"
# brew "lazygit"
# brew "lua-language-server"
# brew "luajit"
# brew "ncdu"
# brew "neovim"
# brew "pipenv"
# brew "plantuml"
# brew "pv"
# brew "pyenv"
# brew "pyenv-virtualenv"
# brew "rust"
# brew "stylua"
# brew "the_silver_searcher"
# brew "tig"
# brew "tldr"
#
# cask "android-commandlinetools"
# cask "android-studio"
# cask "arc"
# cask "chatgpt"
# cask "dash"
# cask "discord"
# cask "docker"
# cask "easy-move-plus-resize"
# cask "figma"
# cask "finicky"
# cask "firefox"
# cask "flutter"
# cask "font-sauce-code-pro-nerd-font"
# cask "gitup"
# cask "google-chrome-canary"
# cask "inkdrop"
# cask "karabiner-elements"
# cask "lens"
# cask "lyricsx"
# cask "min"
# cask "miro"
# cask "obsidian"
# cask "openvpn-connect"
# cask "polypane"
# cask "postman"
# cask "raycast"
# cask "redisinsight"
# cask "responsively"
# cask "squirrel"
# cask "telegram"
# cask "temurin"
