tap "oven-sh/bun"

brew "bat"
brew "btop"
brew "bun"
brew "cmake"
brew "cocoapods"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "git-delta"
brew "gnu-sed"
brew "gnupg"
brew "grip" # markdown preview
brew "hadolint"
brew "httpie"
brew "jq"
brew "lazygit"
brew "lua-language-server"
brew "luajit"
brew "ncdu"
brew "neovim"
brew "powerlevel10k"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "stylua"
brew "tig"
brew "tldr"
brew "tmux"
brew "wget"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "alacritty"
cask "alfred"
cask "anytype"
cask "arc"
cask "chatgpt"
cask "docker"
cask "easy-move-plus-resize"
cask "figma"
cask "finicky"
cask "firefox"
cask "font-sauce-code-pro-nerd-font"
cask "google-chrome"
cask "karabiner-elements"
cask "min"
cask "polypane"
cask "slack"
cask "squirrel"

# Migrating...
#
# brew "ansible"
# brew "asimov"
# brew "gitui"
# brew "google-cloud-sdk"
# brew "graphviz"
# brew "grep"
# brew "ncdu"
# brew "pipenv"
# brew "plantuml"
# brew "pv"
# brew "rust"
# brew "the_silver_searcher"
#
# cask "android-commandlinetools"
# cask "android-studio"
# cask "dash"
# cask "discord"
# cask "flutter"
# cask "gitup"
# cask "google-chrome-canary"
# cask "lens"
# cask "lyricsx"
# cask "min"
# cask "miro"
# cask "obsidian"
# cask "openvpn-connect"
# cask "postman"
# cask "raycast"
# cask "redisinsight"
# cask "responsively"
# cask "telegram"
# cask "temurin"
