git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  screenMode: "normal"
  scrollHeight: 8
  mouseEvents: false
keybinding:
  universal:
    quit: "Q"
    # return : 'q'
