---@type LazyPluginSpec
local VisualMulti = {
  -- https://github.com/mg979/vim-visual-multi
  'mg979/vim-visual-multi',
  event = 'VeryLazy',
  init = function()
    vim.g.VM_default_mappings = 0
    vim.g.VM_maps = {
      ['Add Cursor At Pos'] = ';;\\',
      ['Align Char'] = ';;<',
      ['Align Regex'] = ';;>',
      ['Align'] = ';;a',
      ['Case Conversion Menu'] = ';;C',
      ['Duplicate'] = ';;d',
      ['Find Next'] = ']',
      ['Find Operator'] = 'm',
      ['Find Prev'] = '[',
      ['Find Subword Under'] = '<C-n>',
      ['Find Under'] = '<C-n>',
      ['Goto Next'] = '}',
      ['Goto Prev'] = '{',
      ['Invert Direction'] = 'o',
      ['Merge Regions'] = ';;m',
      ['Numbers Append'] = ';;N',
      ['Numbers'] = ';;n',
      ['Remove Last Region'] = ';;q',
      ['Remove Region'] = 'Q',
      ['Replace Pattern'] = 'R',
      ['Rewrite Last Search'] = ';;r',
      ['Run Ex'] = ';;x',
      ['Run Last Ex'] = ';;X',
      ['Run Last Normal'] = ';;Z',
      ['Run Last Visual'] = ';;V',
      ['Run Macro'] = ';;@',
      ['Run Normal'] = ';;z',
      ['Run Visual'] = ';;v',
      ['Search Menu'] = ';;S',
      ['Seek Next'] = '<C-f>',
      ['Seek Prev'] = '<C-b>',
      ['Select All'] = ';;A',
      ['Show Registers'] = ';;"',
      ['Skip Region'] = 'q',
      ['Split Regions'] = ';;s',
      ['Start Regex Search'] = ';;/',
      ['Surround'] = 'S',
      ['Switch Mode'] = '<Tab>',
      ['Toggle Whole Word'] = ';;w',
      ['Transpose'] = ';;t',
      ['Visual Add'] = ';;a',
      ['Visual All'] = ';;A',
      ['Visual Cursors'] = ';;c',
      ['Visual Find'] = ';;f',
      ['Visual Regex'] = ';;/',
      ['Visual Subtract'] = ';;s',
      ['Zero Numbers Append'] = ';;0N',
      ['Zero Numbers'] = ';;0n',
    }
  end,
}

return VisualMulti
