import = [
  '~/.config/alacritty/catppuccin-macchiato.toml',
]

[env]
TERM = 'xterm-256color'

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = 'Buttonless'
opacity = 0.9

[font]
# normal = { family = 'SauceCodePro Nerd Font Mono', style = 'Regular' }
normal = { family = 'SauceCodePro Nerd Font', style = 'Regular' }
size = 12

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
