[shell]
program = '/bin/zsh'

[window]
option_as_alt = 'OnlyLeft'

[scrolling]
multiplier = 1

[bell]
command = { program = 'osascript', args = ['-e', 'beep'] }

[[hints.enabled]]
command = 'open'
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true, mods = 'Command' }
binding = { key = 'u', mods = 'Control|Shift' }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
